### PR TITLE
use `Sync.once` opt the lazy init func

### PR DESCRIPTION
**Pull request by imxyb**

### CODE REVIEW

**Comment by stevenh** [comment]
Cleaner but does it result in better performance?

Could you create a benchmark to prove either way?

**Comment by imxyb** [comment]
> Cleaner but does it result in better performance?
> 
> Could you create a benchmark to prove either way?

I have used BenchmarkPoolGet to compare, and the performance is almost the same as before. This change can make the code cleaner and more concise

**Comment by FZambia** [comment]
btw, `sync.Once` internally [also has a fast path](https://golang.org/src/sync/once.go#L40) based on the atomic comparison.

**Comment by imxyb** [comment]
> btw, `sync.Once` internally [also has a fast path](https://golang.org/src/sync/once.go#L40) based on the atomic comparison.

yes, i know, this change is only make the code more cleaner and readable

**Review by stevenh — APPROVED** [review]

**Comment by stevenh** [comment]
Thanks for confirming.

**Pull request merged**
